import "@/app/globals.css";

export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <main className="mx-8 my-4">{children}</main>
      </body>
    </html>
  );
}
